## WRITE ADDITION, SUBTRACTION, MULTIPLICATION, AND DIVISION OPERATIONS THAT RESULT IN THE NUMBER 8.
## BE SURE TO ENCLOSE YOUR OPERATIONS IN PRINT() CALLS TO SEE THE RESULTS. YOUR OUTPUT SHOULD SIMPLY BE
## FOUR LINES WITH THE NUMBER 8 PEARING ON EACH LINE.

print(5+3)
print(2*4)
print(16/2)
print(9-1)